'use strict';
// cas-ccps/curriculum/canvas-cartridges/ is generated by
// tools/cas-ccps/build-canvas-cartridge.js from the teacher's own lessons
// (build-lesson-assignments.js; the pacing-guide unit builder is still tested). Pins: the committed cartridges match the
// generator byte for byte; every manifest reference resolves to a file in the
// package; each course gets one module per unit it takes, in pacing order;
// lesson pages leave out the other course's parts; and assignments send
// students to their CAS document and take a link. Also covers the zip and
// .docx readers the generator is built on.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { build, buildCourse } = require('../../tools/cas-ccps/build-canvas-cartridge.js');
const rubrics = require('../../tools/cas-ccps/build-unit-rubrics.js');
const { loadDecks } = require('../../tools/cas-ccps/lesson-cards.js');
const { readZip, writeZip } = require('../../tools/cas-ccps/zip.js');
const { parseDocumentXml, textOf } = require('../../tools/cas-ccps/lesson-cards.js');

const DIR = path.join(__dirname, '..', '..', 'cas-ccps', 'curriculum', 'canvas-cartridges');
const built = build();
const course = (code) => {
  const c = built.find((x) => x.name === code + '.imscc');
  return { c, files: Object.fromEntries(c.entries.map(([p, v]) => [p, String(v)])) };
};
// The pacing-guide unit cartridges (buildCourse), no longer committed since
// the courses moved to the teacher's own lessons, still tested as a builder.
const unitData = rubrics.load();
const unitDecks = loadDecks();
const unitCourse = (code) => {
  const c = buildCourse(code, unitDecks, unitData);
  return { c, files: Object.fromEntries(c.entries.map(([p, v]) => [p, String(v)])) };
};

test('the committed cartridges match the generator', () => {
  const onDisk = fs.readdirSync(DIR).filter((f) => f.endsWith('.imscc')).sort();
  assert.deepEqual(onDisk, ['8175.imscc', '8177.imscc'], 'run: node tools/cas-ccps/build-canvas-cartridge.js');
  built.forEach((c) => assert.ok(fs.readFileSync(path.join(DIR, c.name)).equals(writeZip(c.entries)),
    c.name + ' is out of date; run: node tools/cas-ccps/build-canvas-cartridge.js'));
});

test('every manifest item points at a resource, and every resource file is in the package', () => {
  built.forEach((c) => {
    const unpacked = readZip(fs.readFileSync(path.join(DIR, c.name)));
    const manifest = unpacked['imsmanifest.xml'].toString('utf8');
    const resources = {};
    for (const m of manifest.matchAll(/<resource identifier="([^"]+)"[^>]*>\s*<file href="([^"]+)"/g)) resources[m[1]] = m[2];
    const refs = [...manifest.matchAll(/identifierref="([^"]+)"/g)].map((m) => m[1]);
    assert.ok(refs.length > 0);
    refs.forEach((r) => assert.ok(resources[r], c.name + ': ' + r + ' has no resource'));
    Object.values(resources).forEach((href) => assert.ok(unpacked[href], c.name + ': ' + href + ' missing'));
    const ids = [...manifest.matchAll(/identifier="([^"]+)"/g)].map((m) => m[1]);
    assert.equal(new Set(ids).size, ids.length, c.name + ': identifiers are unique');
  });
});

test('the cartridges carry the teacher\'s lessons: one module and assignment per lesson, in teaching order', () => {
  const titles = (code) => course(code).c.modules.map((m) => m.title);
  assert.equal(titles('8175').length, 36);
  assert.match(titles('8175')[0], /^L01 EVOLUTION OF MARKETING/);
  assert.match(titles('8175')[5], /^L06 SKILL DEVELOPMENT PLAN/);
  assert.ok(titles('8177').includes('Venue Operations & The Employee Handbook'));
  built.forEach((c) => c.modules.forEach((m) => assert.equal(m.items.length, 1, m.title)));
});

test('a lesson assignment is the Canvas text without its title and submission lines, and sends students to CAS', () => {
  const { files } = course('8175');
  const xml = Object.entries(files).filter(([p]) => p.endsWith('assignment.xml'));
  assert.equal(xml.length, 36);
  xml.forEach(([p, x]) => {
    assert.match(x, /<gradable points_possible="100">true<\/gradable>/, p);
    assert.match(x, /<format type="url"\/>/, p);
    assert.match(x, /CAS document for this lesson/, p);
    assert.doesNotMatch(x, /Title: Assignment|Bell Ringer|Grading Tip|Pacing guide dates/, p);
  });
  const l06 = xml.map(([, x]) => x).find((x) => /L06 SKILL DEVELOPMENT PLAN/.test(x));
  assert.match(l06, /Write a 100-word plan/);
  assert.match(l06, /&lt;h3&gt;The Task&lt;\/h3&gt;/, '"The Task:" becomes a heading');
  assert.doesNotMatch(l06, /Submit your plan as a Text Entry/, 'Canvas text-entry submission is replaced by the CAS link');
  const eh = Object.values(course('8177').files).find((x) => /Cavalier Shop Operations Brief|Part 1: The Team/.test(x));
  assert.match(eh, /Part 4: The Rush/);
  assert.match(eh, /Use these terms accurately/);
});

test('unit builder: one module per unit the course takes, in pacing order, each with a lesson page and an assignment', () => {
  const units = (code) => unitCourse(code).c.modules.map((m) => m.title.split(' · ')[0]);
  assert.deepEqual(units('8175'), ['S0-U1', 'S0-U2', 'S0-U3', 'S1-U1', 'S1-U2', 'S2-U1', 'S2-U2', 'S3-U1', 'S3-U2',
    'S4-U1', 'S5-U1', 'S5-U2', 'S6-U1', 'S6-U2', 'S7-U1', 'S7-U2', 'S8-U1', 'S9-U1']);
  assert.deepEqual(units('8177'), ['S0-U1', 'S0-U2', 'S0-U3', 'S1-U1', 'S1-U2', 'S1-U3', 'S2-U1', 'S3-U1', 'S3-U2',
    'S4-U1', 'S5-U1', 'S5-U2', 'S6-U1', 'S6-U2', 'S7-U2', 'S8-U1', 'S8-U2', 'S9-U1']);
  ['8175', '8177'].forEach((code) => unitCourse(code).c.modules.forEach((m) => {
    assert.ok(m.items.some((i) => /: lesson$/.test(i.title)), m.title);
    assert.equal(m.items.filter((i) => !/: lesson$|overview$/.test(i.title)).length, 1, m.title);
  }));
  assert.deepEqual(unitCourse('8177').c.modules.find((m) => m.title.startsWith('S7-U2')).items[0].title, 'Stage 7 overview');
});

test('unit builder: a lesson page leaves out the other course\'s objective, tasks, role, extension and competencies', () => {
  const p = unitCourse('8175').files['wiki_content/s1-u1-lesson.html'];
  assert.match(p, /8175 Marketing goes deeper on/);
  assert.match(p, /Tasks — 8175/);
  assert.doesNotMatch(p, /8177 Management|Tasks — 8177|8177 role|Manager traits and functions \(Tasks 40–42\)/);
  assert.doesNotMatch(p, /<td>8177<\/td>/, 'no 8177 competency rows');
  assert.doesNotMatch(p, /SCR<\/th>|<td>__<\/td>/, 'the blank SCR column is dropped');
  const q = unitCourse('8177').files['wiki_content/s1-u1-lesson.html'];
  assert.match(q, /8177 Management goes deeper on/);
  assert.doesNotMatch(q, /8175 Marketing|Tasks — 8175|8175 role|<td>8175<\/td>/);
});

test('unit builder: an assignment sends the student to their CAS document and takes a link', () => {
  const { files } = unitCourse('8177');
  const xml = Object.entries(files).filter(([p]) => p.endsWith('assignment.xml'));
  assert.equal(xml.length, 18);
  xml.forEach(([p, x]) => {
    assert.match(x, /CAS document for this unit/, p);
    assert.doesNotMatch(x, /response zone below/, p);
  });
});

test('writeZip output reads back, and is the same bytes every time', () => {
  const entries = [['a/b.txt', 'hello'], ['c.xml', Buffer.from('<x/>')]];
  const z = writeZip(entries);
  assert.ok(z.equals(writeZip(entries)));
  const back = readZip(z);
  assert.equal(back['a/b.txt'].toString(), 'hello');
  assert.equal(back['c.xml'].toString(), '<x/>');
});

test('parseDocumentXml keeps paragraphs, bold runs, list items and nested tables', () => {
  const xml = '<w:document><w:body>' +
    '<w:p><w:r><w:rPr><w:b/></w:rPr><w:t>Bold</w:t></w:r><w:r><w:t xml:space="preserve"> plain &amp; more</w:t></w:r></w:p>' +
    '<w:p><w:pPr><w:pStyle w:val="ListParagraph"/></w:pPr><w:r><w:t>item</w:t></w:r></w:p>' +
    '<w:tbl><w:tr><w:tc><w:p><w:r><w:t>k</w:t></w:r></w:p></w:tc><w:tc>' +
    '<w:tbl><w:tr><w:tc><w:p><w:r><w:t>inner</w:t></w:r></w:p></w:tc></w:tr></w:tbl>' +
    '</w:tc></w:tr></w:tbl></w:body></w:document>';
  const b = parseDocumentXml(xml);
  assert.equal(b.length, 3);
  assert.deepEqual(b[0].runs, [{ text: 'Bold', bold: true }, { text: ' plain & more', bold: false }]);
  assert.equal(b[1].list, true);
  assert.equal(b[2].type, 'table');
  assert.equal(textOf(b[2].rows[0][0]), 'k');
  assert.equal(b[2].rows[0][1][0].type, 'table');
  assert.equal(textOf(b[2].rows[0][1]), 'inner');
});
