'use strict';
// cas-ccps/curriculum/unit-rubrics/ is generated by
// tools/cas-ccps/build-unit-rubrics.js from the pacing guide and
// CompetencyRubrics.json. Pins that the committed files match the
// generator, and the shape Flow 1's intake needs.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { build } = require('../../tools/cas-ccps/build-unit-rubrics.js');

const DIR = path.join(__dirname, '..', '..', 'cas-ccps', 'curriculum', 'unit-rubrics');

test('the committed unit rubrics match the generator', () => {
  const files = build();
  const onDisk = fs.readdirSync(DIR).filter((f) => f.endsWith('.md') && f !== 'README.md').sort();
  assert.deepEqual(onDisk, Object.keys(files).sort(), 'run: node tools/cas-ccps/build-unit-rubrics.js');
  onDisk.forEach((f) => assert.equal(fs.readFileSync(path.join(DIR, f), 'utf8'), files[f],
    f + ' is out of date; run: node tools/cas-ccps/build-unit-rubrics.js'));
});

test('one rubric per unit a course takes; none for the other course\'s only-units', () => {
  const files = build();
  assert.ok(files['S7-U1_8175.md'] && !files['S7-U1_8177.md'], 'S7-U1 is 8175 only');
  assert.ok(files['S8-U2_8177.md'] && !files['S8-U2_8175.md'], 'S8-U2 is 8177 only');
  assert.ok(files['S1-U3_8177.md'] && !files['S1-U3_8175.md'], 'S1-U3 is 8177 only');
});

test('each rubric clears the intake\'s 100-character minimum and lists its competencies', () => {
  Object.entries(build()).forEach(([name, doc]) => {
    const rubric = /## Rubric\n\n```\n([\s\S]*?)\n```/.exec(doc)[1];
    assert.ok(rubric.length >= 100, name);
    assert.match(rubric, /^COMPETENCIES ASSESSED: (817[57]-\d+)(, 817[57]-\d+)*$/m, name);
    assert.match(doc, /## Prompt template\n\n```\n[\s\S]+?\n```/, name);
  });
});

test('the vocabulary comes from the lesson card, not the card table labels in the pacing guide', () => {
  Object.entries(build()).forEach(([name, doc]) => {
    assert.doesNotMatch(doc, /What students do|Distribution chain node|Role context|STRENGTHS/, name);
  });
  assert.match(build()['S1-U1_8175.md'], /Use these terms accurately: Sports, entertainment & events industry, Hospitality, Experience economy, Esports, Niche event, Stakeholder\./);
});
