'use strict';
// cas-ccps/curriculum/unit-rubrics/ is generated by
// tools/cas-ccps/build-unit-rubrics.js from the pacing guide and
// CompetencyRubrics.json. Pins that the committed files match the
// generator, and the shape Flow 1's intake needs.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { build } = require('../../tools/cas-ccps/build-unit-rubrics.js');

const DIR = path.join(__dirname, '..', '..', 'cas-ccps', 'curriculum', 'unit-rubrics');

test('the committed unit rubrics match the generator', () => {
  const files = build();
  const onDisk = fs.readdirSync(DIR).filter((f) => f.endsWith('.md') && f !== 'README.md').sort();
  assert.deepEqual(onDisk, Object.keys(files).sort(), 'run: node tools/cas-ccps/build-unit-rubrics.js');
  onDisk.forEach((f) => assert.equal(fs.readFileSync(path.join(DIR, f), 'utf8'), files[f],
    f + ' is out of date; run: node tools/cas-ccps/build-unit-rubrics.js'));
});

test('one rubric per unit a course takes; none for the other course\'s only-units', () => {
  const files = build();
  assert.ok(files['S7-U1_8175.md'] && !files['S7-U1_8177.md'], 'S7-U1 is 8175 only');
  assert.ok(files['S8-U2_8177.md'] && !files['S8-U2_8175.md'], 'S8-U2 is 8177 only');
  assert.ok(files['S1-U3_8177.md'] && !files['S1-U3_8175.md'], 'S1-U3 is 8177 only');
});

test('each rubric clears the intake\'s 100-character minimum and lists its competencies', () => {
  Object.entries(build()).forEach(([name, doc]) => {
    const rubric = /## Rubric\n\n```\n([\s\S]*?)\n```/.exec(doc)[1];
    assert.ok(rubric.length >= 100, name);
    assert.match(rubric, /^COMPETENCIES ASSESSED: (817[57]-\d+)(, 817[57]-\d+)*$/m, name);
    assert.match(doc, /## Prompt template\n\n```\n[\s\S]+?\n```/, name);
  });
});

test('the vocabulary comes from the lesson card, not the card table labels in the pacing guide', () => {
  Object.entries(build()).forEach(([name, doc]) => {
    assert.doesNotMatch(doc, /What students do|Distribution chain node|Role context|STRENGTHS/, name);
  });
  assert.match(build()['S1-U1_8175.md'], /Use these terms accurately: Sports, entertainment & events industry, Hospitality, Experience economy, Esports, Niche event, Stakeholder\./);
});

test('the pacing guide\'s vocabulary matches the lesson cards (JSON and CSV)', () => {
  const sync = require('../../tools/cas-ccps/sync-pacing-vocabulary.js');
  const out = sync.build();
  const CUR = path.join(__dirname, '..', '..', 'cas-ccps', 'curriculum');
  assert.equal(fs.readFileSync(path.join(CUR, 'PacingGuide_CAS_Context.json'), 'utf8'), out.json,
    'run: node tools/cas-ccps/sync-pacing-vocabulary.js');
  assert.equal(fs.readFileSync(path.join(CUR, 'PacingGuide_CAS_Context.csv'), 'utf8'), out.csv,
    'run: node tools/cas-ccps/sync-pacing-vocabulary.js');
  const units = JSON.parse(out.json).pacing_guide;
  units.forEach((u) => assert.doesNotMatch(u.key_vocabulary, /What students do|Distribution chain node|Role context|Career plan component|STRENGTHS/, u.lesson_unit_id));
  assert.match(units.find((u) => u.lesson_unit_id === 'S1-U1').key_vocabulary, /^Sports, entertainment & events industry, Hospitality/);
  assert.equal(sync.pyJson([{ term: 'Café — x', definition: 'a "b"' }]), '[{"term": "Caf\\u00e9 \\u2014 x", "definition": "a \\"b\\""}]');
});

test('each assignment is the lesson card\'s planned work: its work product, the course\'s role and extension', () => {
  const files = build();
  Object.entries(files).forEach(([name, doc]) => {
    assert.match(doc, /^PLANNED WORK PRODUCT: \S/m, name);
    assert.match(doc, /^What you will make: \S/m, name);
    assert.doesNotMatch(doc, /Choose an organization in sports, entertainment or events/, name + ' still has the old generic prompt');
  });
  const m = files['S1-U1_8175.md'];
  assert.match(m, /PLANNED WORK PRODUCT: Industry landscape document: a one-page brief per student/);
  assert.match(m, /COURSE ROLE: Marketing rotation students focus on consumer-facing trends/);
  assert.match(m, /- Hospitality \(Task 46\): how does hospitality function as a marketing tool\?/);
  assert.doesNotMatch(m, /Organizational chart \(Task 44\)/, '8177\'s extension stays out of the 8175 rubric');
  const g = files['S1-U1_8177.md'];
  assert.match(g, /COURSE ROLE: Management specialization students map industry management functions/);
  assert.match(g, /- Organizational chart \(Task 44\): students draft the conglomerate org chart/);
  assert.match(files['S0-U1_8175.md'], /^COURSE ROLE: \S/m, 'Stage 0 uses the shared Role context row');
});
