'use strict';
// kos-personal/rtp-core-router/notebook-sources/ holds the notebook edition
// of each persona doc, generated by tools/kos-personal/build-notebook-personas.js
// (RTP notebook plan, Phase 2 step 1). Pins: the committed editions match the
// generator; each opens with its persona's core block, which quotes the doc's
// own Mandatory Prefix and stays short; every heading outside a code fence
// names the persona; and apart from the preamble and those heading prefixes,
// the edition is the canonical doc unchanged.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { build } = require('../../tools/kos-personal/build-notebook-personas.js');

const ROUTER = path.join(__dirname, '..', '..', 'kos-personal', 'rtp-core-router');
const editions = build();

test('the committed notebook persona editions match the generator', () => {
  const onDisk = fs.readdirSync(path.join(ROUTER, 'notebook-sources')).filter((f) => /^PERSONA_.*\.md$/.test(f)).sort();
  assert.deepEqual(onDisk, editions.map((e) => e.file).sort(), 'run: node tools/kos-personal/build-notebook-personas.js');
  editions.forEach((e) => assert.equal(fs.readFileSync(path.join(ROUTER, 'notebook-sources', e.file), 'utf8'), e.text,
    e.file + ' is out of date; run: node tools/kos-personal/build-notebook-personas.js'));
});

test('each edition opens with a short core block that quotes the doc\'s own prefix', () => {
  editions.forEach((e) => {
    const src = fs.readFileSync(path.join(ROUTER, e.file), 'utf8');
    const prefix = /\*\*Mandatory Prefix:\*\*\s*`([^`]+)`/.exec(src)[1];
    const core = e.text.slice(e.text.indexOf('## ' + e.name + ' · Core'), e.text.indexOf('\n---'));
    assert.ok(core.length > 500 && [...core].length <= 2400, e.file + ': core is ' + [...core].length + ' characters');
    assert.ok(core.includes('`' + prefix + '`'), e.file);
    assert.match(core, /\*\*Hard rules:\*\*/, e.file);
    assert.ok(e.text.indexOf('## ' + e.name + ' · Core') < e.text.indexOf('## ' + e.name + ' · 1.'), e.file + ': core comes first');
  });
});

test('every heading outside a code fence names the persona', () => {
  editions.forEach((e) => {
    let fence = false;
    e.text.split('\n').slice(1).forEach((l) => {
      if (/^\s*(```|~~~)/.test(l)) fence = !fence;
      if (!fence && /^#{2,6}\s/.test(l)) assert.match(l, new RegExp('^#{2,6} ' + e.name + ' · '), e.file + ': ' + l);
    });
  });
});

test('apart from the preamble and heading prefixes, an edition is the canonical doc unchanged', () => {
  editions.forEach((e) => {
    const src = fs.readFileSync(path.join(ROUTER, e.file), 'utf8');
    const lines = src.split('\n');
    const rule = lines.findIndex((l, i) => i > 0 && /^-{3,}\s*$/.test(l));
    const original = lines.slice(rule).join('\n').replace(/\n*$/, '\n');
    const body = e.text.slice(e.text.indexOf('\n' + lines[rule] + '\n') + 1)
      .split('\n').map((l) => l.replace(new RegExp('^(#{2,6}) ' + e.name + ' · '), '$1 ')).join('\n');
    assert.equal(body, original, e.file);
    assert.doesNotMatch(e.text, /Version notes from|Gemini Gem System Prompt/, e.file + ': preamble dropped');
  });
});
