'use strict';
// Tests for cas-ccps/scripts/53_AssignmentSeeder.js: LIVE TeacherMatrix
// assignments written from the repo's unit rubrics (53b, generated by
// tools/cas-ccps/build-unit-rubrics.js) without Studio Flow 1. Pins: a
// preview writes nothing; the TeacherMatrix tab is added when the matrix
// lacks it (seen live); each row is LIVE with its prompt-template Doc and
// text competency IDs; a unit already in the matrix is never written again;
// and the roster import's fetchAssignment_ (02) finds the seeded row.

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const { loadGasFiles } = require('../harness/gas-sandbox');

const S = (f) => path.join(__dirname, '..', '..', 'cas-ccps', 'scripts', f);
const FILES = ['00_SharedConfig.js', '22_LessonContextHandler.js', '23_StudentProfileManager.js',
  '31_PacingGuideManager.js', '02_Form1_IntakeAndWorkspaceGenerator.js', '29_StudentContextAggregator.js',
  '53b_UnitAssignmentData.js', '53_AssignmentSeeder.js'].map(S);
const EXPOSE = ['previewAssignmentSeed', 'seedAssignments_', 'fetchAssignment_', 'getConfig_', 'UNIT_ASSIGNMENTS'];
const TEACHER = 'owner.teacher@ccpsnet.net';

function setup() {
  const { exported, sandbox } = loadGasFiles(FILES, EXPOSE);
  const props = sandbox.PropertiesService.getScriptProperties();
  const ledger = sandbox.SpreadsheetApp.create('Central Ledger');
  sandbox.SpreadsheetApp._registry.set(ledger.getId(), ledger);
  props.setProperty('CENTRAL_LEDGER_SS_ID', ledger.getId());
  props.setProperty('TEACHER_EMAIL', TEACHER);
  // The live matrix: the confirmation form's sheet, no TeacherMatrix tab.
  const matrix = sandbox.SpreadsheetApp.create('Teacher Matrix');
  sandbox.SpreadsheetApp._registry.set(matrix.getId(), matrix);
  matrix.insertSheet('_CONFIG');
  const reg = ledger.insertSheet('MatrixRegistry');
  reg.appendRow(['TeacherName', 'TeacherEmail', 'MatrixSsId', 'Created']);
  reg.appendRow(['Mr. Owner', TEACHER, matrix.getId(), new Date()]);
  return { exported, sandbox, props, matrix };
}

test('preview lists S1-U1 for both courses and writes nothing', () => {
  const { exported, matrix } = setup();
  const r = exported.seedAssignments_({ apply: false, units: ['S1-U1'] });
  assert.deepEqual(r.planned.map((p) => p.configId), ['CAS-S1-U1-8175', 'CAS-S1-U1-8177']);
  assert.equal(matrix.getSheetByName('TeacherMatrix'), null);
});

test('seed adds the TeacherMatrix tab and writes LIVE rows the roster import can find', () => {
  const { exported, sandbox, matrix } = setup();
  const r = exported.seedAssignments_({ apply: true, units: ['S1-U1'] });
  assert.equal(r.written, 2);
  const tab = matrix.getSheetByName('TeacherMatrix');
  const rows = tab.getRange(2, 1, tab.getLastRow() - 1, 20).getValues();
  const a = exported.UNIT_ASSIGNMENTS['S1-U1_8175'];
  const row = rows[0];
  assert.equal(row[0], 'CAS-S1-U1-8175');
  assert.equal(row[1], a.unitName);
  assert.equal(row[11], 'LIVE');
  assert.equal(row[14], '8175 Sports Entertainment and Event Marketing');
  assert.deepEqual(row.slice(15, 19), a.milestoneCompetencyIds);
  assert.equal(row[19], 'S1-U1');
  assert.equal(row[8], a.definitionOfDone);
  const doc = sandbox.DocumentApp.openById(row[12]);
  assert.equal(doc.getBody().getText(), a.promptText);

  const cfg = exported.getConfig_();
  const found = exported.fetchAssignment_(cfg, 'CAS-S1-U1-8177');
  assert.equal(found.courseName, '8177 Sports Entertainment and Event Management');
  assert.equal(found.teacherEmail, TEACHER);
});

test('a unit already in the matrix is never written again', () => {
  const { exported, matrix } = setup();
  exported.seedAssignments_({ apply: true, units: ['S1-U1'] });
  const again = exported.seedAssignments_({ apply: true, units: ['S1-U1', 'S1-U3'] });
  assert.equal(again.written, 1, 'only S1-U3 (8177 only) is new');
  assert.deepEqual(again.skipped.map((s) => s.configId).sort(),
    ['CAS-S1-U1-8175', 'CAS-S1-U1-8177', 'CAS-S1-U3-8175']);
  assert.equal(matrix.getSheetByName('TeacherMatrix').getLastRow(), 4);
});

test('SEED_UNITS chooses the units when set', () => {
  const { exported, props } = setup();
  props.setProperty('SEED_UNITS', 'S1-U2');
  const r = exported.previewAssignmentSeed();
  assert.deepEqual(r.planned.map((p) => p.configId), ['CAS-S1-U2-8175', 'CAS-S1-U2-8177']);
});

test('every generated assignment has four milestones and a competency on the first', () => {
  const { exported } = setup();
  Object.entries(exported.UNIT_ASSIGNMENTS).forEach(([key, a]) => {
    assert.equal(a.milestones.length, 4, key);
    assert.ok(a.milestones.every(Boolean), key);
    assert.match(a.milestoneCompetencyIds[0], /^817[57]-\d+$/, key);
  });
});
